# Generated by Django 5.0.9 on 2024-10-18 17:55

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRegimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_pt', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255, null=True)),
                ('name_es', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Regimen Fiscal',
                'verbose_name_plural': 'Categorías de Regímenes Fiscales',
            },
        ),
        migrations.CreateModel(
            name='LegalEntityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(default='MX', editable=False, max_length=2)),
            ],
            options={
                'verbose_name': 'Regimen Capital',
                'verbose_name_plural': 'Regímenes Capitales',
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='TaxRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_pt', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255, null=True)),
                ('name_es', models.CharField(max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(default='MX', editable=False, max_length=2)),
            ],
            options={
                'verbose_name': 'Regimen Fiscal',
                'verbose_name_plural': 'Regímenes Fiscales',
                'unique_together': {('code', 'name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(default='MX', editable=False, max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('ext_number', models.CharField(max_length=10)),
                ('int_number', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misc.legalentitycategory')),
                ('tax_regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misc.taxregime')),
            ],
            options={
                'verbose_name': 'Entidad Legal',
                'verbose_name_plural': 'Entidades Legales',
            },
        ),
    ]
