# Generated by Django 5.0.9 on 2024-10-18 20:23

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxregimecategory',
            name='country',
            field=django_countries.fields.CountryField(default='MX', editable=False, max_length=2),
        ),
    ]
