# Generated by Django 5.0.9 on 2024-10-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_taxregimecategory_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxregimecategory',
            old_name='country',
            new_name='country_code',
        ),
    ]
