# Generated by Django 5.0.9 on 2024-10-18 20:26

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('misc', '0003_rename_country_taxregimecategory_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxregimecategory',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tax_regime_categories', to='cities_light.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxregimecategory',
            name='country_code',
            field=django_countries.fields.CountryField(default='MX', max_length=2),
        ),
    ]
