# Generated by Django 5.0.9 on 2024-10-18 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('misc', '0004_taxregimecategory_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalentity',
            options={'verbose_name': 'Legal Entity', 'verbose_name_plural': 'Legal Entities'},
        ),
        migrations.AlterModelOptions(
            name='taxregime',
            options={'verbose_name': 'Tax Regime', 'verbose_name_plural': 'Tax Regimes'},
        ),
        migrations.AlterModelOptions(
            name='taxregimecategory',
            options={'verbose_name': 'Tax Regime Category', 'verbose_name_plural': 'Tax Regime Categories'},
        ),
        migrations.RemoveField(
            model_name='taxregimecategory',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='country',
            field=models.ForeignKey(default=158, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='legalentitycategory',
            name='country',
            field=models.ForeignKey(default=158, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_categories', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='country',
            field=models.ForeignKey(default=158, on_delete=django.db.models.deletion.PROTECT, related_name='tax_regimes', to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregimecategory',
            name='country',
            field=models.ForeignKey(default=158, on_delete=django.db.models.deletion.PROTECT, related_name='tax_regime_categories', to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='taxregimecategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregimecategory',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregimecategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregimecategory',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregimecategory',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxregimecategory',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
