# Generated by Django 5.0.9 on 2024-10-18 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('misc', '0005_alter_legalentity_options_alter_taxregime_options_and_more'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalentitycategory',
            options={'verbose_name': 'Legal Entity Category', 'verbose_name_plural': 'Legal Entity Categories'},
        ),
        migrations.AddField(
            model_name='legalentity',
            name='organization',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misc.legalentitycategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='country',
            field=models.ForeignKey(default=158, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities', to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='ext_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='External number'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='int_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Internal number'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='state',
            field=models.CharField(max_length=255, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='tax_id',
            field=models.CharField(max_length=30, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='tax_regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misc.taxregime', verbose_name='Tax regime'),
        ),
        migrations.AlterField(
            model_name='legalentitycategory',
            name='country',
            field=models.ForeignKey(default=158, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_categories', to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='legalentitycategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
